input {
  elastic_agent {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts                       => "${ELASTIC_HOSTS}"
    user                        => "${ELASTIC_USER}"
    password                    => "${ELASTIC_PASSWORD}"
    ssl_certificate_authorities => "/usr/share/logstash/certs/ca.crt"
    index                       => "logstash-test-%{+YYYY.MM.dd}"
  }
}
