input {
  file {
    path => "/usr/share/logstash/ingest_data/**/*"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  # tom for nu
}

output {
  elasticsearch {
    hosts => "${ELASTIC_HOSTS}"
    user => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
    #ssl_certificate_authorities => "/usr/share/logstash/certs/ca/ca.crt"
    ssl_certificate_authorities => "/usr/share/logstash/certs/ca.crt"
    index => "logstash-test-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
